const BASIC_BLOUSE_FRONT = {
  id: "basic-blouse-front",
  name: "Basic Blouse Front",
  version: 1,
  unitsNote: "Formulas run after inputs are converted to millimeters.",
  measurements: {
    bust: { unit: "inch", required: true, label: "Bust", default: 36 },
    shoulder: { unit: "inch", required: true, label: "Shoulder", default: 14 },
    neck: { unit: "inch", required: true, label: "Neck", default: 6 },
    armhole: { unit: "inch", required: true, label: "Armhole", default: 16 },
    length: { unit: "inch", required: true, label: "Blouse length", default: 15 },
    sleeveLength: { unit: "inch", required: true, label: "Sleeve length", default: 8 },
    seamAllowance: { unit: "inch", required: true, label: "Seam allowance", default: 0.5 },
  },
  formulas: {
    frontWidth: "bust / 4",
    shoulderWidth: "shoulder / 2",
    neckWidth: "neck / 2",
    neckDepth: "bust / 10",
    armholeDepth: "bust / 6",
    shoulderSlope: "shoulderWidth * 0.12",
    armholeBulge: "armhole / 16",
    backNeckWidth: "neck / 5",
    backNeckDepth: "bust / 24",
    sleeveCapHeight: "armholeDepth * 0.5",
    sleeveBicep: "armhole / 2",
    sleeveCuff: "sleeveBicep * 0.72",
    facingWidth: "neck / 4",
  },
  pieces: [
    {
      id: "front",
      name: "Front",
      seamAllowanceMm: "seamAllowance",
      points: [
        { id: "cfNeck", x: "0", y: "neckDepth" },
        { id: "neckShoulder", x: "neckWidth", y: "0" },
        { id: "shoulderEnd", x: "shoulderWidth", y: "shoulderSlope" },
        { id: "underarm", x: "frontWidth", y: "armholeDepth" },
        { id: "hemSide", x: "frontWidth", y: "length" },
        { id: "hemCf", x: "0", y: "length" },
      ],
      segments: [
        { id: "centerFront", type: "line", from: "hemCf", to: "cfNeck", role: "fold" },
        {
          id: "neck",
          type: "bezier",
          role: "seam",
          start: "cfNeck",
          end: "neckShoulder",
          control1: {
            x: "cfNeck.x + neckWidth * 0.3",
            y: "cfNeck.y - neckDepth * 0.8",
          },
          control2: {
            x: "neckShoulder.x - neckWidth * 0.3",
            y: "neckShoulder.y + neckDepth * 0.25",
          },
        },
        { id: "shoulder", type: "line", from: "neckShoulder", to: "shoulderEnd", role: "seam" },
        {
          id: "armhole",
          type: "bezier",
          role: "seam",
          start: "shoulderEnd",
          end: "underarm",
          control1: {
            x: "shoulderEnd.x + (frontWidth - shoulderWidth) * 0.08",
            y: "shoulderEnd.y + (armholeDepth - shoulderSlope) * 0.45",
          },
          control2: {
            x: "underarm.x - (frontWidth - shoulderWidth) * 0.65 - armholeBulge * 0.15",
            y: "underarm.y - (armholeDepth - shoulderSlope) * 0.15",
          },
        },
        { id: "sideSeam", type: "line", from: "underarm", to: "hemSide", role: "seam" },
        { id: "hem", type: "line", from: "hemSide", to: "hemCf", role: "seam" },
      ],
      notches: [
        { id: "shoulderNotch", at: "shoulderEnd", along: "armhole", lengthMm: 6 },
        { id: "underarmNotch", at: "underarm", along: "sideSeam", lengthMm: 6 },
      ],
      grainline: {
        id: "frontGrain",
        x: "frontWidth * 0.35",
        y1: "length * 0.3",
        y2: "length * 0.72",
      },
    },
    {
      id: "back",
      name: "Back",
      points: [
        { id: "backCfNeck", x: "0", y: "backNeckDepth" },
        { id: "backNeckShoulder", x: "backNeckWidth", y: "0" },
        { id: "backShoulderEnd", x: "shoulderWidth", y: "shoulderSlope" },
        { id: "backUnderarm", x: "frontWidth", y: "armholeDepth" },
        { id: "backHemSide", x: "frontWidth", y: "length" },
        { id: "backHemCf", x: "0", y: "length" },
      ],
      segments: [
        { id: "backCenter", type: "line", from: "backHemCf", to: "backCfNeck", role: "fold" },
        {
          id: "backNeck",
          type: "bezier",
          role: "seam",
          start: "backCfNeck",
          end: "backNeckShoulder",
          control1: { x: "backCfNeck.x + backNeckWidth * 0.35", y: "backCfNeck.y - backNeckDepth * 0.65" },
          control2: { x: "backNeckShoulder.x - backNeckWidth * 0.25", y: "backNeckShoulder.y + backNeckDepth * 0.35" },
        },
        { id: "backShoulder", type: "line", from: "backNeckShoulder", to: "backShoulderEnd", role: "seam" },
        {
          id: "backArmhole",
          type: "bezier",
          role: "seam",
          start: "backShoulderEnd",
          end: "backUnderarm",
          control1: { x: "backShoulderEnd.x + (frontWidth - shoulderWidth) * 0.1", y: "backShoulderEnd.y + (armholeDepth - shoulderSlope) * 0.4" },
          control2: { x: "backUnderarm.x - (frontWidth - shoulderWidth) * 0.55", y: "backUnderarm.y - (armholeDepth - shoulderSlope) * 0.12" },
        },
        { id: "backSide", type: "line", from: "backUnderarm", to: "backHemSide", role: "seam" },
        { id: "backHem", type: "line", from: "backHemSide", to: "backHemCf", role: "seam" },
      ],
      notches: [{ id: "backUnderarmNotch", at: "backUnderarm", along: "backSide", lengthMm: 6 }],
      grainline: { id: "backGrain", x: "frontWidth * 0.35", y1: "length * 0.3", y2: "length * 0.72" },
    },
    {
      id: "sleeve",
      name: "Sleeve",
      points: [
        { id: "capLeft", x: "-sleeveBicep / 2", y: "sleeveCapHeight" },
        { id: "capTop", x: "0", y: "0" },
        { id: "capRight", x: "sleeveBicep / 2", y: "sleeveCapHeight" },
        { id: "cuffRight", x: "sleeveCuff / 2", y: "sleeveLength" },
        { id: "cuffLeft", x: "-sleeveCuff / 2", y: "sleeveLength" },
      ],
      segments: [
        { id: "sleeveSideLeft", type: "line", from: "cuffLeft", to: "capLeft", role: "seam" },
        {
          id: "sleeveCap",
          type: "bezier",
          role: "seam",
          start: "capLeft",
          end: "capRight",
          control1: { x: "capLeft.x + sleeveBicep * 0.22", y: "capTop.y" },
          control2: { x: "capRight.x - sleeveBicep * 0.22", y: "capTop.y" },
        },
        { id: "sleeveSideRight", type: "line", from: "capRight", to: "cuffRight", role: "seam" },
        { id: "sleeveHem", type: "line", from: "cuffRight", to: "cuffLeft", role: "seam" },
      ],
      notches: [{ id: "capNotch", at: "capTop", along: "sleeveCap", lengthMm: 6 }],
      grainline: { id: "sleeveGrain", x: "0", y1: "sleeveCapHeight", y2: "sleeveLength * 0.75" },
    },
    {
      id: "neckFacing",
      name: "Neck facing",
      points: [
        { id: "faceCf", x: "0", y: "neckDepth * 0.15" },
        { id: "faceShoulder", x: "neckWidth", y: "0" },
        { id: "faceOuterShoulder", x: "neckWidth + facingWidth * 0.15", y: "facingWidth" },
        { id: "faceOuterCf", x: "0", y: "facingWidth + neckDepth * 0.2" },
      ],
      segments: [
        { id: "faceCenter", type: "line", from: "faceOuterCf", to: "faceCf", role: "fold" },
        {
          id: "faceNeck",
          type: "bezier",
          role: "seam",
          start: "faceCf",
          end: "faceShoulder",
          control1: { x: "faceCf.x + neckWidth * 0.3", y: "faceCf.y - neckDepth * 0.25" },
          control2: { x: "faceShoulder.x - neckWidth * 0.25", y: "faceShoulder.y + neckDepth * 0.2" },
        },
        { id: "faceShoulderEdge", type: "line", from: "faceShoulder", to: "faceOuterShoulder", role: "seam" },
        { id: "faceOuter", type: "line", from: "faceOuterShoulder", to: "faceOuterCf", role: "seam" },
      ],
      notches: [],
      grainline: null,
    },
  ],
};

export { BASIC_BLOUSE_FRONT };
